language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
before_install:
  - apt-get update
  - apt-get install snmp -y
  - apt-get install snmp-mibs-downloader -y
  - apt-get install libsnmp-dev -y
  - apt-get install gcc python-dev -y
install:
  - pip install -r requirements.txt
script: py.test