language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
sudo: required
before_install:
  - apt-get update
  - apt-get install apache2 apache2-doc apache2-utils -y
  - service apache2 restart
install:
  - pip install -r requirements.txt
script: py.test