#!/usr/bin/python

import re, sys, ipaddress, datetime


tenant = []
with open('/home/eorochena/big.leases', 'r') as leases_file:
	leases =  leases_file.readlines()
	for line,today in enumerate(leases):
		if datetime.datetime.now().strftime("%Y/%m/%d") in today:
			if "ends" in today:
				tenant.append(leases[line - 2].replace('{', '').replace('lease', '').replace('\n', ''))

#for notwork in subnet:
#	for ip in tenant:
#		if ipaddress.ip_address(u'%s' % ip.replace(' ','')) in ipaddress.ip_network(notwork):
			#print ip,'   ',notwork

			
subnet = []
s_range = []
subnet_range = {}
with open('/home/eorochena/dhcpd.conf', 'r') as dhcpd_file:
	dhcp = dhcpd_file.readlines()
	for line, ip in enumerate(dhcp):
		if 'subnet ' in ip:
			temp = []
			Subnet = ip.split()[1]
			Netmask =  ip.split()[3]
			Network =  ipaddress.IPv4Network(u'%s/%s' % (Subnet, Netmask))
			subnet.append(Network)
			temp.append(Network)
			ip_range = Network[0], ' - ' ,Network[-1]
			network_range = dhcp[line + 9].replace('range ', '').replace(';', '').replace('\n', '').strip().split(' ')
			if network_range[0].split('.')[2] == network_range[1].split('.')[2]:
				total_servers = int(network_range[1].split('.')[3]) - int(network_range[0].split('.')[3]) + 1
			elif network_range[0].split('.')[2] != network_range[1].split('.')[2]:
				difference = int(network_range[1].split('.')[2]) - int(network_range[0].split('.')[2])
				total_servers = int(network_range[1].split('.')[3]) - int(network_range[0].split('.')[3]) + 256 + difference
			else:
				total_servers = 'NULL'
			subnet_range[Network] = ip_range, network_range, total_servers
print subnet_range
		


