#!/usr/bin/python

import re, sys, ipaddress, datetime


tenant = []
with open('/home/eorochena/big.leases', 'r') as leases_file:
	leases =  leases_file.readlines()
	for line,today in enumerate(leases):
		if datetime.datetime.now().strftime("%Y/%m/%d") in today:
			if "ends" in today:
				tenant.append(leases[line - 2].replace('{', '').replace('lease', '').replace('\n', ''))
subnet = []
subnet_range = {}
with open('/home/eorochena/dhcpd.conf', 'r') as dhcpd_file:
	dhcp = dhcpd_file.readlines()
	#dhcp = list(set(badlooking_dhcp)
	for line, ip in enumerate(dhcp):
		if 'subnet ' in ip:
			Subnet = ip.split()[1]
			Netmask =  ip.split()[3]
			Network =  ipaddress.IPv4Network(u'%s/%s' % (Subnet, Netmask))
			subnet.append(Network)
			ip_range = "%s - %s" % (str(Network[0]), str(Network[-1]))
			network_range = dhcp[line + 9].replace('range ', '').replace(';', '').replace('\n', '').strip().split(' ')
			dhcp_range = "%s - %s" % (network_range[0], network_range[1])
			if network_range[0].split('.')[2] == network_range[1].split('.')[2]:
				total_servers = int(network_range[1].split('.')[3]) - int(network_range[0].split('.')[3]) + 1
			elif network_range[0].split('.')[2] != network_range[1].split('.')[2]:
				difference = int(network_range[1].split('.')[2]) - int(network_range[0].split('.')[2])
				total_servers = int(network_range[1].split('.')[3]) - int(network_range[0].split('.')[3]) + 256 + difference
			else:
				total_servers = 'NULL'
			for ipaddr in list(set(tenant)):
				if ipaddress.ip_address(u'%s' % ipaddr.replace(' ','')) in ipaddress.ip_network(Network):
					non_reserved = total_servers - 1
					subnet_range[Network] = "%s, %s, %s, %s, %s" % (Netmask, ip_range, dhcp_range, total_servers, non_reserved)
for key, value in subnet_range.iteritems():
	print key, value
		


